### ISSUE TITLE
Objed activation should honor disabled-modes

### ISSUE THREAD

**Issue by richerve** [clemera/objed#69] opened 2020-03-05 12:17 UTC
I have `(objed-mode +1)` and the default `objed-cmd-alist` value.

objed is disabled in magit with `(setq objed-disabled-modes '(magit-mode))`

When I switch to magit-status, objed-mode is not active, I can for example do `f` and will show the "fetch" transient popup, but if I cancel that pop with `C-g` then the magit-status buffer has objed-mode activated. Not sure why is this happening, I thought it was for the default `(objed-auto-init t)` value but even after disabling that the behaviour is still happening.

I presume then that it has to do with objed not taking into account the disabled-modes list when doing auto-init, but I'm not 100% sure.

Maybe is just a conflict with the magit-status mapping.

If I don't activate objed globally this doesn't happen, of course.

**Comment by richerve** [comment] 2020-03-09 10:10
Friendly ping @clemera

**Comment by clemera** [comment] 2020-03-09 12:00
Thanks for the report, I will look into this on the next weekend

**Comment by clemera** [comment] 2020-03-10 16:58
You have to restart `objed-mode` after changing `objed-auto-init` for the setting to take effect. I have to update the docstring. Thanks!

**Comment by clemera** [comment] 2020-03-10 17:01
In your case you need to set the setting before activating `objed-mode`

**Comment by clemera** [comment] 2020-03-10 18:36
Regarding the problem within magit, I can not reproduce that currently. What magit version are you using?

**Comment by richerve** [comment] 2020-03-11 11:20
Will try to configure auto-init early. Latest magit version uses Transient for the modal menu and that uses `C-g` to close them, previously it used `q` but that changed since some time ago.

What I would like if possible is to have the option to keep auto-init and `objed-cmd-alist` but if I explicitly disabled objed in a mode, neither of those should trigger except for `objed-activate`, like a blacklist for all "automatic" cases.

**Comment by richerve** [comment] 2020-03-11 11:39
After setting `objed-auto-init` to nil before loading the objed package, objed is effectively disabled. With that in place even using any cmd-alist didn't work. I would expect to not have auto-init but still have the option to activate when using any command in cmd-alist. Isn't this the case?

**Comment by clemera** [comment] 2020-03-11 12:04
At the beginning `objed-auto-init` was only for the automatic activation after commands in `objed-cmd-alist`, later I added automatic activation when the user switches the buffer also controlled by that option. I feel I should probably add another user option for the second behavior (especially because the switch buffer behavior has some edge cases where it doesn't work correctly). This would also solve your problem although, I'm still interested why it activates for you when quitting the transient window, which doesn't happen on my side. 

Note that you can always activate objed manually by calling an object command directly like `M-x objed-defun-object` or by `objed-activate` or `objed-activate-object`.

**Comment by richerve** [comment] 2020-03-11 12:26
To clarify, when I set objed-auto-init to nil, it doesn't activates automatically in magit. It works as objed being disabled in terms of automatic detection, both when using the cmd-alist and also the auto-init commands. 

When having `objed-auto-init t`, it doesn't activate immediately after switching to the magit-status buffer but when going from the Transient menu back to the magit-status buffer it auto-activates. I presume it's related to the `switch-buffer` "hook" or any other command that triggers the auto-init feature.

**Comment by clemera** [comment] 2020-03-11 12:48
I understood that correctly I think. For me quitting the transient menu does not activate objed. I have just pushed a commit which will keep the automatic activation via commands of `objed-cmd-alist` but has a separate option to control the activation on buffer change (deactivated by default). If you install via regular melpa you have to wait a bit until that version is picked up by the melpa build bot.

**Comment by richerve** [comment] 2020-03-11 14:00
I'm installing using straight.el so I can pin to an specific commit, thank you.

I think it would be nice to have the auto-init option available but that it will deactivate if the whole mode (or derived modes) are disabled using `objed-disabled-modes`

**Comment by clemera** [comment] 2020-03-11 14:08
With the last commit I made you can still set `objed-auto-init-on-buffer-change`, together with `objed-auto-init` you will have the old behavior. I still can't reproduce the problem with magit/transient, could you post your objed/magit/transient setup? Have you tried to reproduce the bug with `emacs -Q`?

**Comment by richerve** [comment] 2020-03-11 17:30
I'm using [doom emacs](https://github.com/hlissner/doom-emacs), so it may be something there but I doubt it as the objed setup changes faces and a couple of variables (https://github.com/hlissner/doom-emacs/blob/develop/modules/editor/objed/config.el). For magit, I'm not sure right now, there may be something on its setup that is affecting.

Will give it a try with `emacs -Q` later today or tomorrow.

**Comment by richerve** [comment] 2020-03-12 17:25
Just tried the new buffer-change variable and auto-init and works as expected, I can now at least use the cmd commands to activate objed and don't have the auto-activation on buffer change. But again if I activate the new variable `objed-auto-init-on-buffer-change`, then on magit objed is activated every time I move from the transient buffer to the status buffer. Are you sure this is not related to magit internally calling `switch-buffer` and therefore activating objed in the background? In this case is when I said that even the auto-init feature should be disabled if there's an explicit disablement on the mode with `objed-disabled-modes`. No auto-activation should happen in that case, only explicit objed-activate.

**Comment by clemera** [comment] 2020-03-12 18:24
> Are you sure this is not related to magit internally calling switch-buffer and therefore activating objed in the background? 

As I said I can't reproduce the bug I guess this is caused by some things doom does. But you where right the init conditions were inconsistent I fixed that in last commit, maybe your problem is gone now because it's now checking the disabled modes for the auto init on buffer change, too.

**Comment by clemera** [comment] 2020-03-18 12:55
Is it fixed now?

**Comment by richerve** [comment] 2020-03-18 16:49
Sorry for the delay, you can close this it looks it only affects me for the moment and I haven't been able to try it with a clean emacs setup. In any case splitting the feature of auto-init and on buffer change is a very useful thing to have. I'll open a new issue at some point if needed in case I have a full test of the situation.

**Comment by clemera** [comment] 2020-03-20 14:03
OK, feel free to reopen if you can reproduce the problem.

**Closed by clemera** 2020-03-20 14:03 UTC
